backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: public/uploads
public_folder: /uploads
site_url: 'https://victory-ministry.netlify.app/'
collections:
  - label: 'Event'
    name: 'event'
    folder: 'contents/events'
    create: true
    media_folder: '{{media_folder}}'
    public_folder: '{{public_folder}}/{{slug}}'
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Location'
        name: 'location'
        widget: 'string'
      - label: 'Description'
        name: 'description'
        widget: 'text'
      - label: 'Images'
        name: 'images'
        widget: 'list'
        fields:
          - { label: 'Caption', name: 'caption', widget: 'string' }
          - label: 'Image'
            name: 'image'
            format: 'DD MMM YYYY'
            widget: 'image'
  - label: 'Page'
    name: 'page'
    files:
      - label: 'Home'
        name: 'home'
        file: 'contents/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'About'
        name: 'about'
        file: 'contents/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
